modLoader="javafml"
loaderVersion="[@forge_version_major@,)"
license="@license@"
issueTrackerURL="@issues@"
[[mods]]
	modId="@modid@"
	version="@version@"
	displayName="@modname@"
	displayURL="@url@"
	logoFile="@logofile@"
	authors="@authors@"
	description='''@description@'''

#[[dependencies.@modid@]]
#    modId="forge"
#    mandatory=true
#    versionRange="[@forge_version_major@,]"
#    ordering="NONE"
#    side="BOTH"
#
#[[dependencies.@modid@]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[@mc_version@]"
#    ordering="NONE"
#    side="BOTH"