modLoader="javafml"
loaderVersion="[@forge_version_short@,)"
license="@license@"
issueTrackerURL="@issues@"

[[mods]]
	modId="@modid@"
	version="@version@"
	displayName="@modname@"
	displayURL="@url@"
	logoFile="@logofile@"
	authors="@authors@"
    credits="@credits@"
    displayTest="IGNORE_SERVER_VERSION"
	description='''@mod_description@'''

[[dependencies.@modid@]]
    modId="forge"
    mandatory=true
    versionRange="[@forge_version_short@,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.@modid@]]
    modId="minecraft"
    mandatory=true
    versionRange="@mc_version_range@"
    ordering="NONE"
    side="BOTH"