package cyberslas.pathundergates;

import com.google.common.eventbus.EventBus;
import net.minecraftforge.fml.common.*;
import org.apache.logging.log4j.Logger;

public class PathUnderGates extends DummyModContainer {
    public static Logger logger;

    public PathUnderGates() {
        super(new ModMetadata());
        ModMetadata meta = this.getMetadata();
        ModMetadata mcmodMeta = meta;

        logger = FMLLog.log;

        try {
            mcmodMeta = MetadataCollection.from(getClass().getResourceAsStream("/mcmod.info"),"mcmod.info").getMetadataForId("@modid@", null);
        } catch(Exception e) {
            logger.error("mcmod.info parsing error", e);
            mcmodMeta.modId = "BADLOAD";
            mcmodMeta.name = "BADLOAD";
            mcmodMeta.version = "BADLOAD";
        }

        copyMetadata(meta, mcmodMeta);
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register(this);
        return true;
    }

    private void copyMetadata(ModMetadata dest, ModMetadata source) {
        dest.modId = source.modId;
        dest.name = source.name;
        dest.description = source.description;

        dest.url = source.url;
        dest.updateJSON = source.updateJSON;

        dest.logoFile = source.logoFile;
        dest.version = source.version;
        dest.authorList = source.authorList;
        dest.credits = source.credits;
        dest.parent = source.parent;
        dest.screenshots = source.screenshots;

        dest.parentMod = source.parentMod;
        dest.childMods = source.childMods;

        dest.useDependencyInformation = source.useDependencyInformation;
        dest.requiredMods = source.requiredMods;
        dest.dependencies = source.dependencies;
        dest.dependants = source.dependants;
        dest.autogenerated = source.autogenerated;

    }
}
